/**
 * Cross-surface handoffs — T19, T20, T21, T22 (Wave 3).
 *
 * T19 Studio → Coach: when a teacher publishes a syllabus, auto-create
 *     a Coach session per enrolled student with a "day 1" message.
 * T20 Passport → Insight: when a credential is issued, update the
 *     institution dashboard metrics.
 * T21 Marketplace → Studio: when a buyer purchases a lesson plan,
 *     auto-import the syllabus into the buyer's Studio.
 * T22 Classroom Live → Coach: when a live class starts, Coach joins
 *     as a co-teacher (auto-answer questions via student chat).
 */

import type { Env } from '../types';
import { getSupabase } from './supabase';

/**
 * T19: After teacher publishes syllabus, create Coach sessions for all
 * enrolled students with a "day 1" plan.
 *
 * The "day 1" plan is generated by the Curator agent — it references
 * the first week of items and gives a 2-min intro.
 */
export async function handoffSyllabusToCoach(
  env: Env,
  syllabusId: string,
  teacherId: string
): Promise<{ sessions_created: number }> {
  const supabase = getSupabase(env);

  // 1. Load syllabus + items.
  const { data: syllabus } = await supabase
    .from('syllabi')
    .select('id, name, classroom_id, target_exam')
    .eq('id', syllabusId)
    .single();
  if (!syllabus) throw new Error('Syllabus not found');

  // 2. Get enrolled students (via classroom if attached, else nothing).
  let studentIds: string[] = [];
  if (syllabus.classroom_id) {
    const { data: enrollments } = await supabase
      .from('classroom_enrollments')
      .select('student_id')
      .eq('classroom_id', syllabus.classroom_id);
    studentIds = (enrollments ?? []).map((e: any) => e.student_id);
  } else {
    // Fallback: students whose assigned_syllabus matches.
    const { data: assigned } = await supabase
      .from('student_progress_unified')
      .select('student_id')
      .eq('syllabus_id', syllabusId);
    studentIds = (assigned ?? []).map((s: any) => s.student_id);
  }

  if (studentIds.length === 0) return { sessions_created: 0 };

  // 3. Get first 3 items (Day 1 plan).
  const { data: items } = await supabase
    .from('syllabus_items')
    .select('id, sort_order, title, source_type, source_platform_url')
    .eq('syllabus_id', syllabusId)
    .order('sort_order', { ascending: true })
    .limit(3);

  const day1List = (items ?? []).map((i: any, idx: number) =>
    `${idx + 1}. **${i.title}** (${i.source_type})`
  ).join('\n') || '- (no items yet)';

  const day1Message = `Welcome to **${syllabus.name}**! 🎉\n\nHere's your Day 1 plan:\n\n${day1List}\n\nOpen any item and I'll help you work through it. Reply "next" when you're done, or ask me anything.`;

  // 4. Create a Coach session + initial message per student.
  let created = 0;
  for (const studentId of studentIds) {
    const { data: session } = await supabase
      .from('coach_sessions')
      .insert({
        student_id: studentId,
        syllabus_id: syllabusId,
        agent_name: 'tutor',
      })
      .select()
      .single();
    if (!session) continue;
    await supabase.from('coach_messages').insert({
      session_id: session.id,
      role: 'assistant',
      content: day1Message,
      metadata: { source: 't19_handoff', teacher_id: teacherId },
    });
    created++;
  }
  return { sessions_created: created };
}

/**
 * T20: When a credential is issued, increment the issuer's Passport
 * count metric (cached on the institution dashboard).
 */
export async function recordPassportIssuance(
  env: Env,
  credentialId: string
): Promise<void> {
  const supabase = getSupabase(env);
  // Optional: insert into a metric_events table. Skipped if table absent.
  try {
    await supabase.from('metric_events').insert({
      event_type: 'passport_credential_issued',
      entity_id: credentialId,
      recorded_at: new Date().toISOString(),
    });
  } catch {
    // metric_events table may not exist yet — that's OK.
  }
}

/**
 * T21: When a marketplace purchase completes (escrow → released),
 * import the associated syllabus into the buyer's Studio.
 */
export async function importPurchasedSyllabus(
  env: Env,
  purchaseId: string
): Promise<{ new_syllabus_id: string | null }> {
  const supabase = getSupabase(env);

  const { data: purchase } = await supabase
    .from('marketplace_purchases')
    .select('listing_id, buyer_id, escrow_status')
    .eq('id', purchaseId)
    .single();
  if (!purchase || purchase.escrow_status !== 'released') {
    return { new_syllabus_id: null };
  }

  // Load listing → syllabus_id.
  const { data: listing } = await supabase
    .from('marketplace_listings')
    .select('syllabus_id, title, description, exam')
    .eq('id', purchase.listing_id)
    .single();
  if (!listing?.syllabus_id) {
    return { new_syllabus_id: null };
  }

  // Clone the source syllabus for the buyer.
  const { data: srcSyllabus } = await supabase
    .from('syllabi')
    .select('name, description, target_exam, target_score, is_template')
    .eq('id', listing.syllabus_id)
    .single();
  if (!srcSyllabus) return { new_syllabus_id: null };

  const { data: newSyll } = await supabase
    .from('syllabi')
    .insert({
      teacher_id: purchase.buyer_id,
      name: `${srcSyllabus.name} (from marketplace)`,
      description: srcSyllabus.description,
      target_exam: srcSyllabus.target_exam,
      target_score: srcSyllabus.target_score,
      is_template: false,
      is_published: false,
    })
    .select('id')
    .single();
  if (!newSyll) return { new_syllabus_id: null };

  // Clone items.
  const { data: items } = await supabase
    .from('syllabus_items')
    .select('sort_order, title, source_type, source_material_id, source_platform_url')
    .eq('syllabus_id', listing.syllabus_id)
    .order('sort_order');
  if (items && items.length > 0) {
    await supabase.from('syllabus_items').insert(
      (items as any[]).map(i => ({ ...i, syllabus_id: newSyll.id }))
    );
  }

  return { new_syllabus_id: newSyll.id };
}

/**
 * T22: When a live class starts, post a Coach message in the class
 * chat introducing the AI tutor as a co-teacher.
 */
export async function notifyCoachOnClassStart(
  env: Env,
  liveClassId: string,
  syllabusId: string,
  teacherId: string
): Promise<{ sessions_notified: number }> {
  const supabase = getSupabase(env);

  // Get enrolled students.
  const { data: syllabus } = await supabase
    .from('syllabi')
    .select('classroom_id')
    .eq('id', syllabusId)
    .single();
  if (!syllabus?.classroom_id) return { sessions_notified: 0 };

  const { data: enrollments } = await supabase
    .from('classroom_enrollments')
    .select('student_id')
    .eq('classroom_id', syllabus.classroom_id);
  const studentIds = (enrollments ?? []).map((e: any) => e.student_id);

  let notified = 0;
  for (const studentId of studentIds) {
    // Find or create the student's most recent Coach session.
    const { data: sessions } = await supabase
      .from('coach_sessions')
      .select('id')
      .eq('student_id', studentId)
      .order('started_at', { ascending: false })
      .limit(1);
    const sessionId = sessions?.[0]?.id;
    if (!sessionId) continue;

    await supabase.from('coach_messages').insert({
      session_id: sessionId,
      role: 'system',
      content: `A live class just started! Your teacher is live now. I'll be co-teaching — drop your questions here and I'll help between teacher sessions.`,
      metadata: { source: 't22_live_class', live_class_id: liveClassId, teacher_id: teacherId },
    });
    notified++;
  }
  return { sessions_notified: notified };
}