/**
 * Built-in agent tools — Task 1 (Wave 1).
 *
 * Each tool handler has the signature (args, ctx, env) => Promise<unknown>.
 * Tools are registered into a ToolBus by the route handler (see routes/agents.ts).
 *
 * Tools:
 * - rag_search(query, topK=5): vector search over knowledge base
 * - fetch_user_profile(userId): unified_profiles row
 * - fetch_syllabus(syllabusId): syllabus + items
 * - fetch_student_progress(studentId): student_progress_unified row
 */

import type { AgentContext, ToolHandler } from './runtime';
import { searchDocuments } from '../services/rag-search';
import { getSupabase } from '../services/supabase';

/** rag_search(query: string, topK?: number) → RagSearchResult[] */
export const ragSearchTool: ToolHandler = async (args, _ctx, env) => {
  const query = String(args.query ?? '').trim();
  const topK = Math.min(Math.max(Number(args.topK ?? 5), 1), 20);
  if (!query) throw new Error('query required');
  return searchDocuments(env, query, { matchCount: topK });
};

/** fetch_user_profile(userId: string) → unified_profiles row */
export const fetchUserProfileTool: ToolHandler = async (args, _ctx, env) => {
  const userId = String(args.userId ?? '').trim();
  if (!userId) throw new Error('userId required');
  const supabase = getSupabase(env);
  const { data, error } = await supabase
    .from('unified_profiles')
    .select('id, email, display_name, role, target_exam, target_score, current_level')
    .eq('id', userId)
    .single();
  if (error) throw new Error(`fetch_user_profile failed: ${error.message}`);
  return data;
};

/** fetch_syllabus(syllabusId: string) → {syllabus, items} */
export const fetchSyllabusTool: ToolHandler = async (args, _ctx, env) => {
  const syllabusId = String(args.syllabusId ?? '').trim();
  if (!syllabusId) throw new Error('syllabusId required');
  const supabase = getSupabase(env);
  const { data: syllabus, error: sErr } = await supabase
    .from('syllabi')
    .select('*')
    .eq('id', syllabusId)
    .single();
  if (sErr) throw new Error(`fetch_syllabus failed: ${sErr.message}`);
  const { data: items, error: iErr } = await supabase
    .from('syllabus_items')
    .select('id, sort_order, title, source_type, source_material_id, source_platform_url')
    .eq('syllabus_id', syllabusId)
    .order('sort_order', { ascending: true });
  if (iErr) throw new Error(`fetch_syllabus items failed: ${iErr.message}`);
  return { syllabus, items: items ?? [] };
};

/** fetch_student_progress(studentId: string) → student_progress_unified row */
export const fetchStudentProgressTool: ToolHandler = async (args, _ctx, env) => {
  const studentId = String(args.studentId ?? '').trim();
  if (!studentId) throw new Error('studentId required');
  const supabase = getSupabase(env);
  const { data, error } = await supabase
    .from('student_progress_unified')
    .select('*')
    .eq('student_id', studentId)
    .single();
  if (error) throw new Error(`fetch_student_progress failed: ${error.message}`);
  return data;
};

/** Register all built-in tools onto a ToolBus. */
export function registerBuiltinTools(
  bus: import('./runtime').ToolBus,
  _ctx: AgentContext
): void {
  bus.register('rag_search', ragSearchTool);
  bus.register('fetch_user_profile', fetchUserProfileTool);
  bus.register('fetch_syllabus', fetchSyllabusTool);
  bus.register('fetch_student_progress', fetchStudentProgressTool);
}

/** search_catalog(query: string) → marketplace listings — T15 Curator tool.
 *  Stub: returns empty list. Real impl reads from marketplace_listings (T14). */
export const searchCatalogTool: ToolHandler = async (args, _ctx, _env) => {
  const query = String(args.query ?? '').trim();
  if (!query) return [];
  // Real impl will query marketplace_listings table.
  return { query, listings: [], note: 'T15 stub — marketplace_listings table created in T14' };
};

/** create_practice_question(exam, level, topic, type) → question — T16 Tutor tool.
 *  Stub: returns a placeholder question. Real impl persists to practice_questions table. */
export const createPracticeQuestionTool: ToolHandler = async (args, _ctx, _env) => {
  const exam = String(args.exam ?? 'GENERAL');
  const level = String(args.level ?? 'B1');
  const topic = String(args.topic ?? 'general English');
  const type = String(args.type ?? 'multiple_choice');
  // Real impl: call OpenAI with rubric + insert into practice_questions table.
  return {
    exam,
    level,
    topic,
    type,
    question: `[${level} ${exam}] Stub question about ${topic} — generated by T16 stub tool. Real impl in T13.`,
    options: type === 'multiple_choice' ? ['A', 'B', 'C', 'D'] : undefined,
    correct: type === 'multiple_choice' ? 'A' : undefined,
    note: 'T16 stub — full impl in T13 Practice Question Generator',
  };
};

/** fetch_grading_history(studentId) → past grading entries — T17 Examiner tool. */
export const fetchGradingHistoryTool: ToolHandler = async (args, _ctx, env) => {
  const studentId = String(args.studentId ?? '').trim();
  if (!studentId) return [];
  const supabase = getSupabase(env);
  const { data, error } = await supabase
    .from('grading_queue')
    .select('id, exam_type, level, rubric, score, created_at')
    .eq('student_id', studentId)
    .order('created_at', { ascending: false })
    .limit(10);
  if (error) {
    // Table may not exist or be named differently — return empty.
    return [];
  }
  return data ?? [];
};

/** fetch_passport(userId) → user's OSEE Passport credentials — T18 Mentor tool. */
export const fetchPassportTool: ToolHandler = async (args, _ctx, env) => {
  const userId = String(args.userId ?? '').trim();
  if (!userId) return [];
  const supabase = getSupabase(env);
  const { data, error } = await supabase
    .from('passport_credentials')
    .select('id, credential_type, subject_data, issued_at, revoked_at')
    .eq('user_id', userId)
    .is('revoked_at', null)
    .order('issued_at', { ascending: false })
    .limit(20);
  if (error) return [];
  return data ?? [];
};

/** fetch_job_market(role, level) → matching job listings — T18 Mentor tool (stub). */
export const fetchJobMarketTool: ToolHandler = async (args) => {
  const role = String(args.role ?? 'engineer');
  const level = String(args.level ?? 'B2');
  // Stub: returns curated suggestions based on common Indonesia → international paths.
  // Real impl: query job_boards API or partner data.
  const suggestions: Record<string, { path: string; requirements: string; salary_idr: string }[]> = {
    engineer: [
      { path: 'Singapore Tech', requirements: 'IELTS 6.5+ + 3yr experience + tech interview', salary_idr: '80-150M IDR/month' },
      { path: 'Germany Ausbildung', requirements: 'IELTS 5.5 + B1 German + vocational training', salary_idr: '30-50M IDR/month' },
      { path: 'Australia Skilled Visa', requirements: 'IELTS 7.0+ + skills assessment', salary_idr: '100-180M IDR/month' },
    ],
    teacher: [
      { path: 'International Schools', requirements: 'IELTS 7.5 + TEFL + 2yr experience', salary_idr: '15-30M IDR/month' },
      { path: 'Online Tutoring (Cambly, iTalki)', requirements: 'C1+ English + TEFL', salary_idr: '5-15M IDR/month' },
    ],
    nurse: [
      { path: 'Australia RN', requirements: 'IELTS 7.0 (each band 7.0) + AHPRA registration', salary_idr: '120-200M IDR/month' },
      { path: 'UK NHS', requirements: 'IELTS 7.0 (each band 7.0) + OSCE exam', salary_idr: '100-180M IDR/month' },
    ],
    general: [
      { path: 'BPO/Call Centers (English-speaking)', requirements: 'B2 + neutral accent', salary_idr: '5-12M IDR/month' },
      { path: 'Content Writer (Remote)', requirements: 'C1 English + portfolio', salary_idr: '8-20M IDR/month' },
    ],
  };
  const jobs = suggestions[role] ?? suggestions.general;
  return { role, level, jobs, note: 'T18 stub — real impl queries job_boards API.' };
};